### PR TITLE
Fix for windows

### PR DESCRIPTION
**Pull request by jeroenooms**
You can build this library out of the box on windows by linking it against Rzlib.dll that is included with R on windows.

### CODE REVIEW

**Comment by stewid** [comment]
Hi @jeroenooms 

It seems `Rzlib.dll` is no longer included with R (R-devel) on Windows, see https://github.com/krlmlr/r-portable/tree/master/Image/R/bin/i386

The macro ZLIB_LIBS, is recently changed from -lRzlib to -lz, see https://github.com/wch/r-source/commit/44937034c25a9d82103aa48580906089775ad8af

I have successfully built `git2r` on Windows, after downloading `local320.zip` from
http://www.stats.ox.ac.uk/pub/Rtools/libs.html and change `LOCAL_SOFT` in `c:/Program/R/R-3.1.2/etc/i386/Makeconf` and `c:/Program/R/R-3.1.2/etc/x64/Makeconf` to the folder of the
unpacked `local320.zip`.

I have also tested that `git2r` builds on win-builder.

**Comment by jeroenooms** [comment]
Ow good catch. I was not aware they are changing the windows build again.

**Comment by stewid** [comment]
Could this work?

```
Z_LIB = $(shell "${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe" -e \
"cat(ifelse (compareVersion(sprintf('%s.%s', R.version$major, R.version$minor), '3.1.2') > 0, '-lz', '-lRzlib'))"

ifeq "$(WIN)" "64"
PKG_LIBS = -L./winhttp -lws2_32 -lwinhttp-x64 -lrpcrt4 -lole32 -lcrypt32 ($Z_LIB)
PKG_CFLAGS = -I. -Ilibgit2 -Ilibgit2/include -Ihttp-parser -Iwin32 -Iregex \
    -DWIN32 -D_WIN32_WINNT=0x0501 -D__USE_MINGW_ANSI_STDIO=1 -DGIT_WINHTTP \
    -D_FILE_OFFSET_BITS=64 -DGIT_ARCH_64
else
PKG_LIBS = -L./winhttp -lws2_32 -lwinhttp -lrpcrt4 -lole32 -lcrypt32 ($Z_LIB)
PKG_CFLAGS = -I. -Ilibgit2 -Ilibgit2/include -Ihttp-parser -Iwin32 -Iregex \
    -DWIN32 -D_WIN32_WINNT=0x0501 -D__USE_MINGW_ANSI_STDIO=1 -DGIT_WINHTTP \
    -D_FILE_OFFSET_BITS=64 -DGIT_ARCH_32
endif
```

**Comment by stewid** [comment]
Hi @jeroenooms 

Thanks for suggesting the use of `Rzlib.dll`.

I have added the following to `Makevars.win` to use `-lRzlib` if R <= 3.1.2 else `-lz`.
Tested with R 3.1.1, 3.1.2 and winbuilder

```
Z_LIB = $(shell "${R_HOME}/bin${R_ARCH_BIN}/Rscript.exe" -e \
    "cat(ifelse(compareVersion(sprintf('%s.%s', R.version['major'], R.version['minor']), '3.1.2') > 0, '-lz', '-lRzlib'))")

ifeq "$(WIN)" "64"
PKG_LIBS = -L./winhttp -lws2_32 -lwinhttp-x64 -lrpcrt4 -lole32 -lcrypt32 $(Z_LIB)
PKG_CFLAGS = -I. -Ilibgit2 -Ilibgit2/include -Ihttp-parser -Iwin32 -Iregex \
    -DWIN32 -D_WIN32_WINNT=0x0501 -D__USE_MINGW_ANSI_STDIO=1 -DGIT_WINHTTP \
    -D_FILE_OFFSET_BITS=64 -DGIT_ARCH_64
else
PKG_LIBS = -L./winhttp -lws2_32 -lwinhttp -lrpcrt4 -lole32 -lcrypt32 $(Z_LIB)
PKG_CFLAGS = -I. -Ilibgit2 -Ilibgit2/include -Ihttp-parser -Iwin32 -Iregex \
    -DWIN32 -D_WIN32_WINNT=0x0501 -D__USE_MINGW_ANSI_STDIO=1 -DGIT_WINHTTP \
    -D_FILE_OFFSET_BITS=64 -DGIT_ARCH_32
endif
```

**Pull request closed without merging**
