### PR TITLE
Ensure that git2r writes the config file to the correct location on Windows

### PR DESCRIPTION
**Pull request by jdblischak**
## Summary

On Windows, the default location for writing and reading `.gitconfig` differs between `git2r::config` and Git run via PowerShell or Git Bash. This PR implements a fix so that the config file is always written to the same location in the root of the user directory.

## Explanation

On Windows, `git2r::config` with `global = TRUE` saves `.gitconfig` to the user's Documents directory. This is presumably due to the fact `~` maps to `Documents/` on Windows ([source](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#What-are-HOME-and-working-directories_003f)).

```
setwd("C:/Users/john/")
# Using the development version of git2r
packageVersion("git2r")
## [1] '0.21.0.9000'
library("git2r")

normalizePath("~")
## [1] "C:\\Users\\john\\Documents"

# When no Git config files exist
file.exists("C:/Users/john/.gitconfig")
## [1] FALSE
file.exists("C:/Users/john/Documents/.gitconfig")
## [1] FALSE
git_config_files()
##     file path
## 1 system <NA>
## 2    xdg <NA>
## 3 global <NA>
## 4  local <NA>

# git2r::config creates the global config file in Documents/
config(global = TRUE, user.name = "name", user.email = "email")

file.exists("C:/Users/john/.gitconfig")
## [1] FALSE
file.exists("C:/Users/john/Documents/.gitconfig")
## [1] TRUE
git_config_files()
##     file                               path
## 1 system                               <NA>
## 2    xdg                               <NA>
## 3 global C:/Users/john/Documents/.gitconfig
## 4  local                               <NA>
```

Then Git can't find the configuration when run from PowerShell or Git Bash:

```
# PowerShell
PS C:\Users\john> git config --get user.name
PS C:\Users\john> git config --get user.email
```

```
# Git Bash
john@LAPTOP-IRFAT6LT MINGW64 ~
$ git config --get user.name

john@LAPTOP-IRFAT6LT MINGW64 ~
$ git config --get user.email

```

However, if an empty `.gitconfig` exists in the user's root directory, then `git2r::config` writes to this file.

```
setwd("C:/Users/john/")
library("git2r")

# git2r::config writes to the user's root directory if the file already exists
unlink("C:/Users/john/Documents/.gitconfig")
file.create("C:/Users/john/.gitconfig")
## [1] TRUE

config(global = TRUE, user.name = "name", user.email = "email")

file.exists("C:/Users/john/.gitconfig")
## [1] TRUE
file.exists("C:/Users/john/Documents/.gitconfig")
## [1] FALSE
git_config_files()
##     file                     path
## 1 system                     <NA>
## 2    xdg                     <NA>
## 3 global C:/Users/john/.gitconfig
## 4  local                     <NA>
```

And then the config settings are recognized from Git at the command-line:

```
# PowerShell
PS C:\Users\john> git config --get user.name
name
PS C:\Users\john> git config --get user.email
email
```

```
john@LAPTOP-IRFAT6LT MINGW64 ~
$ git config --get user.name
name

john@LAPTOP-IRFAT6LT MINGW64 ~
$ git config --get user.email
email

```

To find the user's actual home directory from R, I used this [suggestion from the R help mailing list](https://stat.ethz.ch/pipermail/r-help/2007-March/128221.html) to use the environment variable `"HOMEDRIVE"`. I didn't also use the environment variable `"HOMEPATH"` because for my own project this failed on AppVeyor (and thus may fail on other Windows machines).

### CODE REVIEW

**Comment by jennybc** [comment]
Very related to #314 #317 #318

**Comment by stewid** [comment]
@jdblischak Thanks, much appreciated.

**Comment by jennybc** [comment]
Based on my research into related matters, I think it's possible that USERPROFILE is the preferred solution.

https://stackoverflow.com/questions/606483/what-is-the-meaning-of-these-windows-environment-variables-homedrive-homepath

**Comment by jennybc** [comment]
Perhaps the `ssh_path()` function from #317 should be renamed and used more general for git/ssh home?

**Comment by stewid** [comment]
> Perhaps the ssh_path() function from #317 should be renamed and used more general for git/ssh home

Agree. @jdblischak do you have time to look into that?

**Comment by jdblischak** [comment]
> Perhaps the ssh_path() function from #317 should be renamed and used more general for git/ssh home?

@jennybc Thanks for the pointer! I agree we don't want to have multiple different ways of solving the same problem.

> Agree. @jdblischak do you have time to look into that?

@stewid Yes! First I am going to investigate if USERPROFILE works for my use cases. If it does, then do you have a preference for how I combine the solutions? Should I refactor `ssh_path` so that the part about finding "home" is in a separate function? My workflowr package has a utility function named [get_home](https://github.com/jdblischak/workflowr/blob/a2fa789241d7245170043c07e5af00bd8ccd6b3b/R/utility.R#L144) that essentially does this. I'd be happy to migrate this function upstream to git2r.

**Comment by jennybc** [comment]
In case it's useful, the bottom of this file shows how usethis is currently finessing these matters:

https://github.com/r-lib/usethis/blob/master/R/edit.R

**Comment by stewid** [comment]
I prefer to have a separate function for finding `home` and please refactor `ssh_path` to use that function.

**Comment by jdblischak** [comment]
Success! USERPROFILE worked on my local Windows machine and on AppVeyor. Thanks for the improved solution @jennybc!

> In case it's useful, the bottom of this file shows how usethis is currently finessing these matters:

@jennybc Yes, thanks for sharing. That's essentially a succinct version of what my `get_home` function tries to accomplish.

> I prefer to have a separate function for finding home and please refactor ssh_path to use that function.

@stewid OK. I'll put some together similar to the suggestion from @jennybc and then refactor.

**Pull request merged**
